graphhopper:
  datareader.file: /data/taiwan-latest.osm.pbf
  graph.location: /data/graphhopper
  custom_models.directory: /data
  profiles:
    - name: car
      custom_model_files: [car.json]
  profiles_ch:
    - profile: car
  import.osm.ignored_highways: footway,construction,cycleway,path,steps
server:
  application_connectors:
    - type: http
      port: 8989
  admin_connectors:
    - type: http
      port: 8990
